apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: matmul-flask:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: PYTHONUNBUFFERED
          value: "1" # Melhora a visualização de logs em tempo real
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        # Verifica se o container está vivo
        livenessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 15
          periodSeconds: 20
        # Verifica se o container está pronto para receber tráfego
        readinessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: matmul-flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050